### ISSUE TITLE
Overwrited packageName to cause "Failed to activate component: adc" while using SAMD21G18A

### ISSUE THREAD

**Issue by librachien** [Microchip-MPLAB-Harmony/csp#1]
https://github.com/Microchip-MPLAB-Harmony/csp/blob/e4efd80e001913373e60f0a66eac792ee17618c9/peripheral/adc_u2204/config/adc.py#L157

--> packageName = "TQFP64"

After remove this line will correct.

**Comment by aethaniel** [comment]
Thanks for reporting.
It is fixed with the v3.2.0 release I just published.
