### ISSUE TITLE
Clock Configurator for e51 not working

### ISSUE THREAD

**Issue by jran-dasa** [Microchip-MPLAB-Harmony/csp#12]
Latest commit of clock configurator (clk_sam_e5x.jar) does not work, at least not with SAME51J19A.
Trying to start it from Harmony configurator does nothing.

Changed clk_sam_e5x.jar to previous version (from 26 July 2019) and it starts fine.
Using Harmony Configurator v3.4.1

**Comment by aethaniel** [comment]
Hi @jran-dasa, thanks for reporting.
This has been converted as internal JIRA ticket to be addressed in next coming CSP v3.7.0 release within few weeks (MH3-30406).

**Comment by dsettu** [comment]
@jran-dasa , I tried it with SAME51J19A using below repo version and clock configuration is launching.
![image](https://user-images.githubusercontent.com/15937220/75946675-be25bf80-5ec3-11ea-8746-61a174ae8a82.png)

Please check if you are using dev_packs v3.6.1 as clock configurator uses data from dev_packs.

**Comment by jran-dasa** [comment]
@dsettu I am using the same set of csp, dev_packs and mhc versions as you are.

**Comment by jran-dasa** [comment]
Exact steps I can use to reproduce:
1. Create new project in MPLAB X 5.30, Harmony 3 project for SAME51J19A
2. Launch Harmony Configurator (DFP 3.2.64 and CMSIS 5.6.0)
3. Tools->Clock Configuration, nothing happens.

I enabled all logging, and have attached log file.
[mhc.log](https://github.com/Microchip-MPLAB-Harmony/csp/files/4305116/mhc.log)

**Comment by dsettu** [comment]
@jran-dasa , We fixed UI manager for handling locale issues. Please use v3.7.1 release.
