### ISSUE TITLE
PIC32MX460F512L

### ISSUE THREAD

**Issue by swampmonster** [Microchip-MPLAB-Harmony/csp#13]
Support for this chip seems to be missing.
Would be nice to have that added.
From the looks of it all the 460 chips are missing.

**Comment by dsettu** [comment]
@swampmonster , PIC32MX33XX/4XX family is currently not supported and will be supported by Oct'20.

**Comment by swampmonster** [comment]
> @swampmonster , PIC32MX33XX/4XX family is currently not supported and will be supported by Oct'20.

I see. That's a bummer but i'll just have to wait then. 
Thanks for the help!
