### ISSUE TITLE
PIC32MZ2048ECM100

### ISSUE THREAD

**Issue by KonssnoK** [Microchip-MPLAB-Harmony/csp#15]
Hello there,
our product uses the PIC32MZ2048ECM100 which doesn't seem to be supported by Harmony3 (i see EF is supported).

What do you recommend?
Using Harmony3 configured for the PIC32MZ2048EFM100 and then changing the drivers (like 8740 to 8720) or use Harmony2?

Reading the changelogs Harmony3 seems to be the best choice due to all the improvements.

Thanks

**Comment by aethaniel** [comment]
@KonssnoK, as you said, Harmony 3 is indeed the best choice at the moment.
Migrating to PIC32MZ/EF is indeed highly recommended.
I would suggest you to reach Microchip Sales to see the best way for you to move forward.
