### ISSUE TITLE
Support for SAM cortex-m3 MCUs

### ISSUE THREAD

**Issue by KhazAkar** [Microchip-MPLAB-Harmony/csp#18]
Hello, I'd want to ask - is it planned to add support for SAM Cortex-M3 MCUs like SAM3U or SAM3X series? They're great small MCUs with tons of capabilities but they can be seen now like little out of support.

**Comment by syamknair** [comment]
Hi @KhazAkar,
As of now, we do not have any plans to support SAM Cortex-M3 MCUs in Harmony 3.

**Comment by KhazAkar** [comment]
It's possible to know why? Just curious about future plans regarding SAM Cortex-M3 MCUs :)

**Comment by syamknair** [comment]
Currently, the focus is on adding support for latest Microchip MCUs (with ARM cortex M0+, M4, M7, M23 cores and MIPS cores) in Harmony 3. You can continue using existing tools and framework for SAM Cortex-M3 MCUs from Microchip, if you decide to use them in your design.
