### ISSUE TITLE
TMR documentation does not match function

### ISSUE THREAD

**Issue by stantheman103** [Microchip-MPLAB-Harmony/csp#19]
In the:
Harmony3\csp\peripheral\tmr_00745\templates\plib_tmr_common.h

The event callback function requires two arguments.
// *****************************************************************************
/* TMR_CALLBACK

  Summary:
    Use to register a callback with the TMR.

  Description:
    When a match is asserted, a callback can be activated.
    Use TMR_CALLBACK as the function pointer to register the callback
    with the match.

  Remarks:
    The callback should look like:
      void callback(handle, context);
	Make sure the return value and parameters of the callback are correct.
*/

typedef void (*TMR_CALLBACK)(uint32_t status, uintptr_t context);

// *****************************************************************************

However in the Harmony3/csp/docs/ it incorrectly only says one argument is required.
* This function is called after period expires */
void TIMER2_EventHandler(uintptr_t context)
{
    /* Toggle LED */
    LED_Toggle();
}

int main(void)
{
    /* Register callback function Timer interrupt */
    TMR2_CallbackRegister(TIMER2_EventHandler,(uintptr_t)NULL);

    /* Start the timer channel 0*/
    TMR2_Start();
}

Could the documentation be changed to match the actual usage?

Best regards,
Robert

**Comment by syamknair** [comment]
@stantheman103 , thank you for the feedback. We will fix the documentation in the upcoming release.

**Comment by syamknair** [comment]
Documentation updated to fix the incorrect callback signature
