### ISSUE TITLE
ANSEL in GPIO Initialize

### ISSUE THREAD

**Issue by edndg** [Microchip-MPLAB-Harmony/csp#2]
ANSEL is not present on Port C of PIC32MZ2048EFM064 but it was generated.

**Comment by aethaniel** [comment]
Issue transfered to its right place. 
@edndg, thanks for reporting. We are checking it.

**Comment by aethaniel** [comment]
@edndg, the issue has been fixed recently and the coming next release will show as you expect.

**Comment by youpko** [comment]
This problem still persists for the PIC32MZ1024EFK064

**Comment by arpananand1** [comment]
> This problem still persists for the PIC32MZ1024EFK064

can you tell the steps to reproduce the issue you are facing?

**Comment by youpko** [comment]
Generate source files for the PIC32MZ1024EFK064
in _plib_gpio.c_ in _GPIO_Initialize_ there is generated code for ANSELCCLR register, but the PIC in question doesn't have analog capabilities on Port C.

**Comment by arpananand1** [comment]
> Generate source files for the PIC32MZ1024EFK064
> in _plib_gpio.c_ in _GPIO_Initialize_ there is generated code for ANSELCCLR register, but the PIC in question doesn't have analog capabilities on Port C.

There is a new release planned very soon, you should see the issue fixed in that release.
