### ISSUE TITLE
AD1CSSL Value gets overwritten

### ISSUE THREAD

**Issue by pustekuchen91** [Microchip-MPLAB-Harmony/csp#22]
Hello,

sometimes when regenerating all harmony files, the value of the AD1CSSL Register will be overwritten with another Value.

I'm using the following configuration for the adc.
![grafik](https://user-images.githubusercontent.com/7147324/93434340-4e5bad00-f8c8-11ea-98b1-8b47c121f4d2.png)

It seems that the configurator doesnt recognize the choosen Input Scan Pins.

PIC32MX450F256H
CSP 3.8.1

**Comment by pustekuchen91** [comment]
After restarting MHC and regenerating he tries to change the value again.
![grafik](https://user-images.githubusercontent.com/7147324/93435908-5ae10500-f8ca-11ea-8b3f-e7ab20a0278e.png)

**Comment by arpananand1** [comment]
@pustekuchen91 is it possible to zip and share the complete mplab project?

**Comment by dsettu** [comment]
@pustekuchen91 , I see that AN2, AN3, AN4 and AN5 channels are enabled for channel scan. It should result in AD1CSSL value of 0x3C. Not sure why the earlier code has 0x38 for AD1CSSL register.

**Comment by pustekuchen91** [comment]
@dsettu your right AN2-5 are enabled and should result in value of 0x3C. This value is already set at the current code (current code = right side). 

MHC wants to replace with 0x38 (left side) (where AN2 is not set).

Maybe i can create a new project next week.

**Comment by dsettu** [comment]
@pustekuchen91 , Please let us know if you see this behavior in new project. thanks.

**Comment by pustekuchen91** [comment]
Hello @dsettu 

i've created a brand new project and configured the adc and generated the harmony files. After that i've closed the MHC and reopened and recreated the files. Merge Strategy: All -> The following changes wants to be made:
![grafik](https://user-images.githubusercontent.com/7147324/93741478-c853a500-fbec-11ea-836b-9ece3f70290a.png)

so the problem is 100% reproducible. I've attached the created project.

[ADC_Bug.zip](https://github.com/Microchip-MPLAB-Harmony/csp/files/5253933/ADC_Bug.zip)

**Comment by prachiap** [comment]
@pustekuchen91 , I can reproduce this issue. AD1CSSL Register value is not calculated correctly. 
It will be fixed in the next release. 

Thanks for reporting this issue.

**Comment by prachiap** [comment]
@pustekuchen91 , I have attached the modified file. Please copy/replace this python file at location:
\csp\peripheral\adc_00755\config

[adc.zip](https://github.com/Microchip-MPLAB-Harmony/csp/files/5256038/adc.zip)

Let us know if this solves the issue.

**Comment by pustekuchen91** [comment]
@prachiap thanks, this fix works! 

Maybe you should take a look at AD1CON3, too. As you can see in the last screenshot of the demo project. AD1CON3 was not included at the initial generation and was added at the second run.

**Comment by prachiap** [comment]
@pustekuchen91 , AD1CON3 register will be generated when the AD1CON3 value is non-zero. Once you save the configurations, AD1CON3 value is getting saved correctly. I do not see that,  this difference is showing again and again. 

Let me know if you see any mismatch in this register value.

**Comment by pustekuchen91** [comment]
@prachiap your right, the difference is not showing again and again. But AD1CON3 was missing at the first generation of the harmony files.

- Create new Project
- Configure as following 
![grafik](https://user-images.githubusercontent.com/7147324/93852498-69f0fa00-fcb2-11ea-8d86-2857acd13be2.png)

After first generation: 

`void ADC_Initialize(void)
{
    AD1CON1CLR = _AD1CON1_ON_MASK;

    AD1CON1 = 0xe4;


    /* Turn ON ADC */
    AD1CON1SET = _AD1CON1_ON_MASK;
}`

as you can see AD1CON3 is missing. I've added a zip file with the xml files after first and second generation. as you can see 
[default.zip](https://github.com/Microchip-MPLAB-Harmony/csp/files/5259630/default.zip)

this part is missing in xml file
![grafik](https://user-images.githubusercontent.com/7147324/93853443-29927b80-fcb4-11ea-88d7-0a3f8e6a66de.png)

**Comment by prachiap** [comment]
@pustekuchen91 , Thanks for the details. 
AD1CON3 value is not getting calculated for the first time. 
Please find attached updated file. Copy it to \csp\peripheral\adc_00755\config

[adc_AD1CON3_fix.zip](https://github.com/Microchip-MPLAB-Harmony/csp/files/5266459/adc_AD1CON3_fix.zip)

**Comment by pustekuchen91** [comment]
@prachiap works for me. thanks for the fix.
