### ISSUE TITLE
PIC32MX440F256H is missing.

### ISSUE THREAD

**Issue by petrozawodsky** [Microchip-MPLAB-Harmony/csp#24]
Hello.

I've installed latest updates, but cannot start Harmony v3 with my PIC32MX440F256H.
Error: Unable to locate ATDF file...

What should I do?

Thanks.

**Comment by arpananand1** [comment]
Hi @petrozawodsky 
support for this family of device was not part of previous release, it will be part of next release. however, you can raise a support request for the same, they should be able to help you.

**Comment by vishalnxt** [comment]
@petrozawodsky , this will be supported in H3 v3.9 release, due mid of Feb.
