### ISSUE TITLE
SAM D5x/E5x Family 16-bit Timer data structure issue

### ISSUE THREAD

**Issue by kick2nick** [Microchip-MPLAB-Harmony/csp#25]
Hello,
Generated tc.h file conatain tc_count16_registers_t structure
This structure has 16-bit long fields "tc_cc".
According to datasheet these fields have 16-bit width.
But in fact it is 32-bit width fields(MPlab IO View and hardware tests with PWM mode).
So we have mistakes in datasheet: addresses and sizes of CC0,CC11,CCBUF0,CCBUF1 for 16-bit TC mode. 
I didn't find any information about this problem in Errata sheet.
Also we have mistakes in Harmony generated code according to datasheet.
Best regards,
Nikolay
![1](https://user-images.githubusercontent.com/58635163/103345838-7fd93c80-4aa3-11eb-90d6-a782861b101c.PNG)
![2](https://user-images.githubusercontent.com/58635163/103345840-8071d300-4aa3-11eb-91d9-d49ad205a9d1.PNG)
![3](https://user-images.githubusercontent.com/58635163/103345841-8071d300-4aa3-11eb-93b9-ed38c456dbce.PNG)
![4](https://user-images.githubusercontent.com/58635163/103345843-8071d300-4aa3-11eb-9f04-50ab6b65a721.PNG)

**Comment by prachiap** [comment]
Hi Nikolay, 

CC, PER Register widths are different for 8-bit/16-bit/32-bit mode in TC. 
In datasheet also, we have different sections and offset given for different modes. 

Do you see any discrepancy in writing to CC or PER registers? 
Do you see any functional issue with period and duty cycle of the generated waveform?

Thanks,
Prachi

![image](https://user-images.githubusercontent.com/47987629/104950896-8a725c00-59e7-11eb-85f2-c3965c97ee29.png)

![image](https://user-images.githubusercontent.com/47987629/104950943-9bbb6880-59e7-11eb-8c7b-c539a3e654da.png)

![image](https://user-images.githubusercontent.com/47987629/104951324-4df33000-59e8-11eb-9856-636e731316db.png)

**Comment by kick2nick** [comment]
Generated code gives me PWM with one clock positive pulse(I set 50% duty in GUI).
When I'm trying to set new value it has no effect.
Pulse duration should be set by CC1 register, but it doesn't change.(see pic. 1)
I noticed that in IO view registers CC0 CC1 have 32-bit widths(for 16-bit timer), so I tried to use 32-bit pointer and it worked.(see pic. 2)
Look at IO view: CC0 addr - 0x1C, CC1 addr -0x20. I don't see such addresses in register summary for all timers.

**Comment by prachiap** [comment]
Based on the code snippet, I believe that you are using MPWM mode to generate PWM waveform. 
In MPWM waveform, CC0 decides period and CC1 decides duty cycle and output should be observed on WO[1] pin. WO[0] output is one always clock pulse irrespective of CC1 value. 

Can you please let me know:
1. Which device are you using?
2. Are you checking WO[1] output?
3. Is waveform frequency coming correctly?

Regards,
Prachi

**Comment by prachiap** [comment]
Hi Nikolay,

Are you able to get correct period and duty on WO[1] pin?
Please let me know if issue still persists. 

Regards,
Prachi

**Comment by vishalnxt** [comment]
@kick2nick , I am closing the ticket as there is no update from your side. If you are still facing the issue, you can reopen the ticket and provide your observations. Thank you.
