### ISSUE TITLE
There is a bug that BSP cannot be mapped in Function Type of Pin Settings.

### ISSUE THREAD

**Issue by hitac10** [Microchip-MPLAB-Harmony/csp#26]
commit 3d2fa677bc59891da79fd2a6fe56771f4ff2abaf

Detail is
https://www.microchip.com/forums/m1157141.aspx

**Comment by arpananand1** [comment]
We are looking into this issue.

**Comment by vishalnxt** [comment]
@hitac10 , this will be fixed in the next release.
