### ISSUE TITLE
NVM Driver Documentation missing function

### ISSUE THREAD

**Issue by michaelidesmi** [Microchip-MPLAB-Harmony/csp#29]
The Library interface documentation for the NVM driver is missing the NVM_QuadWordWrite entry.
Quad Word write is available on PIC32MZ devices and is it already implemented in the harmony driver but not listed in the documentation.

**Comment by arpananand1** [comment]
are you using the latest doc? i can see the mentioned API documented
![image](https://user-images.githubusercontent.com/45998994/118104395-b5e6df80-b3f8-11eb-9062-daf860bd4d77.png)

**Comment by michaelidesmi** [comment]
You are right! I downloaded the CSP again and its there. Sorry for the confusion

**Comment by arpananand1** [comment]
cool. BTW i noticed small mistake in documentation in the return type of the API. we shall be fixing it in next release. FYI
