### ISSUE TITLE
Wrong variable usage in SPI slave tempates

### ISSUE THREAD

**Issue by sznyimi** [Microchip-MPLAB-Harmony/csp#32]
Hi,

In SPI slave templates when it is configured to active low busy pin there is a missing "$" character at the beginning of the lines:

https://github.com/Microchip-MPLAB-Harmony/csp/blob/dcff60254e4ca6df7967f55eb862c5d4f9b2a997/peripheral/spi_01329/templates/plib_spi_slave.c.ftl#L161

https://github.com/Microchip-MPLAB-Harmony/csp/blob/dcff60254e4ca6df7967f55eb862c5d4f9b2a997/peripheral/spi_6088/templates/plib_spix_slave.c.ftl#L106

https://github.com/Microchip-MPLAB-Harmony/csp/blob/dcff60254e4ca6df7967f55eb862c5d4f9b2a997/peripheral/spi_00753/templates/plib_spi_slave.c.ftl#L169

Imre

**Comment by vishalnxt** [comment]
@sznyimi , thanks for reporting the issue. This will be fixed in the 3.10 release.
