### ISSUE TITLE
Accessor to tickCounter in interrupt

### ISSUE THREAD

**Issue by CharleO** [Microchip-MPLAB-Harmony/csp#34]
Missing from functionality in both folders.

**Comment by vishalnxt** [comment]
@CharleO , can you please provide more details on the issue? Which PLIB/driver and which device?

**Comment by CharleO** [comment]
For the ATSAMC20 and ATSAMC21, the interrupt vector `SysTick_Handler` in plib_systick.c has a `systick.tickCounter++;` but can't access parameter because their in not a accessor. I also believe this maybe every `SysTick_Handler` interrupt.

**Comment by vishalnxt** [comment]
@CharleO , thank you for reporting the issue. We have created an internal ticket to provide an API to access the tick counter. The fix will be made available in v3.11 CSP release.
