### ISSUE TITLE
exceptionsHandler.s.ftl

### ISSUE THREAD

**Issue by CharleO** [Microchip-MPLAB-Harmony/csp#35]
IAR EWARM version 9.10.2.
Bad instruction in  lines 48, 49, 50, 52, 54, 77, and 83.

These instruction used in GCC assembler, not in IAR as implemented.

**Comment by jigneshmoradiya1** [comment]
@CharleO , Thanks for reporting the issue. This issue will be resolved in the next version of csp release.

**Comment by CharleO** [comment]
Tested "exceptionsHandler.s" in EWARM version 8.50.9, 9.10.2 and latest 9.30.1 compiled properly.
