### ISSUE TITLE
Harmony Configurator's Pin Configuration and Peripherals availability for SAMD10C14A differs from datasheet

### ISSUE THREAD

**Issue by nicotrozzo** [Microchip-MPLAB-Harmony/csp#40]
Hi,
I'm trying to use SERCOM2 with SAMD10C14's pins 4 and 5 (PA14 and PA15), since the datasheet says they are available as SERCOM-ALT:
![pin mux](https://user-images.githubusercontent.com/37149263/147480857-48e8d72f-4b1a-46dc-9010-4a7993a2484c.png)
However, I have two problems when using the MPLAB Harmony Configurator:
- SERCOM2 isn't available as a Peripheral
- SERCOM2 isn't available as an alternative for these pins
![image](https://user-images.githubusercontent.com/37149263/147481358-386eef24-612e-45e7-9500-b0d5e587f9d9.png)
Maybe I'm getting something wrong from the docs or there is a reason why it's not available, I'm sorry if that's the case, but I couldn't find any of these in the documentation.

**Comment by vishalnxt** [comment]
@nicotrozzo , thank you for reporting the issue. We are looking into it and will get back to you soon.

**Comment by vishalnxt** [comment]
@nicotrozzo , the SAM D10C 14-pin variant does not have SERCOM2 (It only has SERCOM0 and SERCOM1). The SERCOM2 is available only on SAM D10D variants. Please refer to the configuration summary chapter in the datasheet. Based on the configuration summary, the SERCOM2 configuration should be ignored for the SAM D10C 14 pin variant. Hope this clarifies. 
![pin_config](https://user-images.githubusercontent.com/54656680/162882047-6d859dae-0d86-414a-b776-1f99d839bc86.PNG)

**Comment by vishalnxt** [comment]
@nicotrozzo , Since there is no further update from you I am closing this issue. Feel free to reopen it in case you have any further questions.

**Comment by nicotrozzo** [comment]
Yes it's fine, thanks! I'd say it's an issue for the MCU docs, and actually Harmony helped me realize this problem.
