### ISSUE TITLE
Harmony Configurator's Pin Configuration and Peripherals availability for PIC32MK1024MCM100 differs from datasheet

### ISSUE THREAD

**Issue by eg-astrouka** [Microchip-MPLAB-Harmony/csp#43]
Hello,
Harmony Configurator shows available function SCK1 for pin 72 (RB7), 
![image](https://user-images.githubusercontent.com/10513191/161411214-1e5b41dc-2314-4672-a7ec-0fdc3e5f2a7d.png)
but PPS Input Selection in datasheet doesn't have this function
![image](https://user-images.githubusercontent.com/10513191/161411229-df0740dd-704a-47d5-aea7-fe7228441945.png)

**Comment by vishalnxt** [comment]
@eg-astrouka , SCK1 function is fixed to PIN 72 and is not remappable and hence is not part of the remapping table. Pin manager lists all the functions, remappable as well as fixed. You will notice that no code is generated by MHC if SCK1 is selected for PIN 72. Hope this clarifies. I am closing this ticket for now. Feel free to reopen it if you need further clarifications.
