### ISSUE TITLE
SAMD21 I2S

### ISSUE THREAD

**Issue by daytonatw** [Microchip-MPLAB-Harmony/csp#7]
unable use samd21 i2s without "i2s_u2224" sub directory folder in "csp\peripheral" directory

**Comment by dsettu** [comment]
@daytonatw , I2S peripheral library is moved to audio repo. Please clone audio repo to use the I2S peripheral. thanks
https://github.com/Microchip-MPLAB-Harmony/audio/tree/master/peripheral
