### ISSUE TITLE
Released csp requires PIC32CX-SG41_DFP v1.4.136 which is not released.

### ISSUE THREAD

**Issue by ashish-mchp** [Microchip-MPLAB-Harmony/csp#75]
This is unacceptable that a dependency is unavailable.

**Comment by jigneshmoradiya1** [comment]
@ashish-mchp, This issue is fixed in the csp v3.19.6 release which has PIC32CX-SG41_DFP v1.5.140 dependency. Hence please use the csp v3.19.6 or latest csp release.
