### ISSUE TITLE
TSENS peripheral missing

### ISSUE THREAD

**Issue by Odry01** [Microchip-MPLAB-Harmony/csp#76]
Hi, I want to use TSENS peripheral in MPLAB MCC Harmony project with SAMC21E18A microcontroller. When I followed the course at [Microchip University](https://mu.microchip.com/sam-and-pic32-peripheral-deep-dive) and saw in the chapter TSENS - MCC Configuration this:

![image](https://github.com/user-attachments/assets/a5e73d31-dd5e-410b-add6-a51805970e2c)

but when I want to use this peripheral in my project, I only have this:

![image](https://github.com/user-attachments/assets/dc26b88f-4e2f-4068-946b-19f210a40c70)

I don't have this peripheral in the peripherals menu, yet in the video course and used. I also tried to create a project with the same microcontroller as in the video, but unfortunately I did not find it there either. It wasn't even in the list of peripherals when I looked here on GitHub in the "peripheral" folder. I have MCC v5.5.1 and MPLAB 6.20 installed with the latest csp update - 3.19.6. Why don't I have the TSENS peripheral available and is there any chance it will be back in a future update?

**Comment by jigneshmoradiya1** [comment]
@Odry01 , Thanks for reporting this issue. TSENS PLIB will be available in the next csp v3.20.0 release.

**Comment by Odry01** [comment]
Thank you very much
