### ISSUE TITLE
PIC32MX795F512L JTAG NOT Disable in SYS_Initialize Routuine

### ISSUE THREAD

**Issue by eastWillow** [Microchip-MPLAB-Harmony/csp#8]
### Problem
![image](https://user-images.githubusercontent.com/8100986/73904783-1a52ef00-48d8-11ea-8aa4-ceb5d583f66f.png)
![image](https://user-images.githubusercontent.com/8100986/73904995-d14f6a80-48d8-11ea-9c30-a2b9b271b1c3.png)

I didnt open the JTAG function but the GPIO is still not working.

schematic:
![image](https://user-images.githubusercontent.com/8100986/73904886-774ea500-48d8-11ea-8663-524dd9a862c2.png)
real:
![image](https://user-images.githubusercontent.com/8100986/73904965-b250d880-48d8-11ea-8e6e-eee9b66ee51c.png)

### HOW to Resolve
I refer this forum post
https://www.microchip.com/forums/m734345.aspx
`DDPCONbits.JTAGEN = 0;`

Add the code:
![image](https://user-images.githubusercontent.com/8100986/73905086-23908b80-48d9-11ea-9a7d-962b55a61bc6.png)
then this will working
![image](https://user-images.githubusercontent.com/8100986/73905109-3905b580-48d9-11ea-9d92-cbdd6d1a06b7.png)

### Harmony 2 
I find in the Harmony 2 the code generator will generate the JTAG Disable Routine
![image](https://user-images.githubusercontent.com/8100986/73905203-7cf8ba80-48d9-11ea-9c14-7122c54e33e8.png)
`SYS_DEVCON_JTAGDisable();`

**Comment by arpananand1** [comment]
thanks for reporting, we will fix this issue.

**Comment by aethaniel** [comment]
@dsettu, please provide status here once fixed.

**Comment by arpananand1** [comment]
the issue has been fixed, it will be part of next release.
