### ISSUE TITLE
PIC32MX460F512L support

### ISSUE THREAD

**Issue by dpslwk** [Microchip-MPLAB-Harmony/csp#9]
Looking for support to be added for the MX460 please?

Any ETA?
Is there a guide of how i can help add this support my self? files to copy edit and add? happy to PR if its easy

**Comment by dsettu** [comment]
@dpslwk , We have not yet added support for PIC32MX3XX/4XX devices in Harmony 3. Our current plan is to add in CQ3'20.  If needed early, please submit service request ( https://microchipsupport.force.com/) to help prioritize on it based on business opportunity. Thank you.
